baseURL = "/"
languageCode = "zh-cn"
title = "MACCMS 静态化站点.." 

# 1. 明确指定主题名称（这是 Submodule 模式的关键）
theme = "hugo-theme-gallery"

# 2. 确保首页显示 movies 目录下的内容
mainSections = ["movies"] 

[params]
  description = "MACCMS 数据成功迁移到 Hugo 静态网站。"